In [2]:
import pandas as pd
import numpy as np

In [138]:
df=pd.read_excel("GlasgowJobs.xlsx")#.drop(columns=df.columns[0])

In [139]:
df.head(5)

,Title,Company,Location,Link,Status,salary,Description
0,Assistant General Manager,Stravaigin,Glasgow G12,https://uk.indeed.com/viewjob?jk=990c1b1d66698dc5,EmployerActive 4 days ago,"£31,000 - £35,000 a year",To implement and maintain training schedule an...
1,Retail Assistant Manager,French Connection,Glasgow G1,https://uk.indeed.com/viewjob?jk=109b5c4ad56f924b,EmployerActive 4 days ago,"£21,000 - £23,000 a year",The ability to excel in a commercially focused...
2,Assistant Venue Manager,VEGA,Glasgow G2,https://uk.indeed.com/viewjob?jk=e7bfca102a9f49a8,Posted11 days ago,"£26,000 a year",We are looking for someone who loves to coach ...
3,Trainee Assistant Manager,Savoy Nightclub,Glasgow G2,https://uk.indeed.com/viewjob?jk=cff3fe3553c380e5,PostedToday,£10 - £15 an hour,Day to day running of the business.
4,Assistant Manager- Gordon Street Coffee,Gordon St Coffee - Glasgow,Glasgow G1,https://uk.indeed.com/viewjob?jk=774b2a4fc750822e,Posted3 days ago,Not Declared,"This is a full-time role, ideal for someone fr..."

Now we gonna use regex to split in groups the salary and extract the value to can use the numbers in a future.

In [140]:
df[["Starter_Salary","Top_salary"]]=df["salary"].str.extract(r"(£\d{2},*\d*)?(?:.*)?(£\d*,*\d*)")
df

,Title,Company,Location,Link,Status,salary,Description,Starter_Salary,Top_salary
0,Assistant General Manager,Stravaigin,Glasgow G12,https://uk.indeed.com/viewjob?jk=990c1b1d66698dc5,EmployerActive 4 days ago,"£31,000 - £35,000 a year",To implement and maintain training schedule an...,"£31,000","£35,000"
1,Retail Assistant Manager,French Connection,Glasgow G1,https://uk.indeed.com/viewjob?jk=109b5c4ad56f924b,EmployerActive 4 days ago,"£21,000 - £23,000 a year",The ability to excel in a commercially focused...,"£21,000","£23,000"
2,Assistant Venue Manager,VEGA,Glasgow G2,https://uk.indeed.com/viewjob?jk=e7bfca102a9f49a8,Posted11 days ago,"£26,000 a year",We are looking for someone who loves to coach ...,NaN,"£26,000"
3,Trainee Assistant Manager,Savoy Nightclub,Glasgow G2,https://uk.indeed.com/viewjob?jk=cff3fe3553c380e5,PostedToday,£10 - £15 an hour,Day to day running of the business.,£10,£15
4,Assistant Manager- Gordon Street Coffee,Gordon St Coffee - Glasgow,Glasgow G1,https://uk.indeed.com/viewjob?jk=774b2a4fc750822e,Posted3 days ago,Not Declared,"This is a full-time role, ideal for someone fr...",NaN,NaN
...,...,...,...,...,...,...,...,...,...
145,Assistant Manager - Flannels,Flannels,Glasgow G34,https://uk.indeed.com/viewjob?jk=6cb507636987a6da,PostedPosted 30+ days ago,"£25,250 - £35,000 a year","Trend aware, fashion conscious and well presen...","£25,250","£35,000"
146,"Assistant Manager, Gordon Street Coffee",The Foundation Group (Glendola Leisure),Glasgow G1,https://uk.indeed.com/viewjob?jk=37462b8b1beb1b87,PostedPosted 3 days ago,"£24,440 a year","This is a full-time role, ideal for someone fr...",NaN,"£24,440"
147,"Assistant Manager, Cash Settlements & Confirma...",Lloyds Banking Group,Hybrid remote in London,https://uk.indeed.com/viewjob?jk=531dcc20cc7f4e22,PostedPosted 12 days ago,"£38,632 - £48,290 a year",Ability to work accurately and efficiently acr...,"£38,632","£48,290"
148,Assistant/Trainee Property Manager - Career op...,Scottish Property Jobs,Glasgow,https://uk.indeed.com/viewjob?jk=1ae0e67091c5250e,PostedPosted 9 days ago,"£21,000 - £22,000 a year","If you have good customer service skills, stro...","£21,000","£22,000"
149,Assistant Manager,Five Guys,Edinburgh+48 locations,https://uk.indeed.com/viewjob?jk=f786a26d3fed1958,PostedPosted 6 days ago,"£28,750 a year",An achievable quarterly bonus scheme worth up ...,NaN,"£28,750"

Probably is a way in the last step to do that when is not a range the number appear in the first column and not in the second but i could not think on nothing so i just gonna do the next step to fix that.

In [144]:
df["Starter_Salary"].fillna(df["Top_salary"],inplace=True) 
df.drop("salary",axis=1)

,Title,Company,Location,Link,Status,Description,Starter_Salary,Top_salary
0,Assistant General Manager,Stravaigin,Glasgow G12,https://uk.indeed.com/viewjob?jk=990c1b1d66698dc5,EmployerActive 4 days ago,To implement and maintain training schedule an...,"£31,000","£35,000"
1,Retail Assistant Manager,French Connection,Glasgow G1,https://uk.indeed.com/viewjob?jk=109b5c4ad56f924b,EmployerActive 4 days ago,The ability to excel in a commercially focused...,"£21,000","£23,000"
2,Assistant Venue Manager,VEGA,Glasgow G2,https://uk.indeed.com/viewjob?jk=e7bfca102a9f49a8,Posted11 days ago,We are looking for someone who loves to coach ...,"£26,000","£26,000"
3,Trainee Assistant Manager,Savoy Nightclub,Glasgow G2,https://uk.indeed.com/viewjob?jk=cff3fe3553c380e5,PostedToday,Day to day running of the business.,£10,£15
4,Assistant Manager- Gordon Street Coffee,Gordon St Coffee - Glasgow,Glasgow G1,https://uk.indeed.com/viewjob?jk=774b2a4fc750822e,Posted3 days ago,"This is a full-time role, ideal for someone fr...",NaN,NaN
...,...,...,...,...,...,...,...,...
145,Assistant Manager - Flannels,Flannels,Glasgow G34,https://uk.indeed.com/viewjob?jk=6cb507636987a6da,PostedPosted 30+ days ago,"Trend aware, fashion conscious and well presen...","£25,250","£35,000"
146,"Assistant Manager, Gordon Street Coffee",The Foundation Group (Glendola Leisure),Glasgow G1,https://uk.indeed.com/viewjob?jk=37462b8b1beb1b87,PostedPosted 3 days ago,"This is a full-time role, ideal for someone fr...","£24,440","£24,440"
147,"Assistant Manager, Cash Settlements & Confirma...",Lloyds Banking Group,Hybrid remote in London,https://uk.indeed.com/viewjob?jk=531dcc20cc7f4e22,PostedPosted 12 days ago,Ability to work accurately and efficiently acr...,"£38,632","£48,290"
148,Assistant/Trainee Property Manager - Career op...,Scottish Property Jobs,Glasgow,https://uk.indeed.com/viewjob?jk=1ae0e67091c5250e,PostedPosted 9 days ago,"If you have good customer service skills, stro...","£21,000","£22,000"
149,Assistant Manager,Five Guys,Edinburgh+48 locations,https://uk.indeed.com/viewjob?jk=f786a26d3fed1958,PostedPosted 6 days ago,An achievable quarterly bonus scheme worth up ...,"£28,750","£28,750"